 import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
 import Navbar from "./_Components/Navbar/Navbar";
import Footer from "./_Components/Footer/Footer";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { SessionProvider } from "next-auth/react";
import Sessionprovider from "./_Components/Sessionprovider/Sessionprovider";
import { Toaster } from "sonner";
import { CartContextProvider } from "./Cartcontext/Cartcontext";
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col">
       <Sessionprovider >
      <CartContextProvider>
      

          <Navbar/>
        <main className="flex-grow">{children}</main>
        <Toaster richColors position="top-right" />
        <Footer/>

      </CartContextProvider>
       </Sessionprovider>
      
        </body>
    </html>
  );
}
